# Generated by Django 2.0.3 on 2018-04-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_dia', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dia',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.IntegerField(primary_key=True, serialize=False)),
                ('hr_inicio', models.CharField(max_length=2)),
                ('hr_fin', models.CharField(max_length=2)),
                ('tot_hrs', models.CharField(max_length=2)),
                ('id_dia', models.ForeignKey(db_column='id_dia', on_delete=django.db.models.deletion.CASCADE, to='disponibilidad.Dia')),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
    ]
