# Generated by Django 2.0.3 on 2018-04-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='id_docente',
            field=models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
    ]
