# Generated by Django 2.0.3 on 2018-04-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tu', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=30)),
                ('id_tu', models.ForeignKey(db_column='id_tu', on_delete=django.db.models.deletion.CASCADE, to='usuario.TipoUsuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
