# Generated by Django 2.0.3 on 2018-04-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id_dat_academicos', models.IntegerField(primary_key=True, serialize=False)),
                ('mencion_grado', models.CharField(max_length=60)),
                ('centro_estudios', models.CharField(max_length=60)),
                ('pais_estudios', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datos_academicos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_docente', models.CharField(max_length=50)),
                ('ape_docente', models.CharField(max_length=50)),
                ('codigo_docente', models.CharField(max_length=10)),
                ('dni_docente', models.CharField(max_length=8)),
                ('email_docente', models.CharField(max_length=70)),
                ('celular_docente', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=1)),
                ('pagina_web', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('pais', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('sunedu_le', models.CharField(max_length=2)),
                ('categoria', models.CharField(max_length=30)),
                ('regimen_dedicacion', models.CharField(max_length=30)),
                ('cv', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='TipoGrado',
            fields=[
                ('id_tip_grado', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom_tip_grado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipo_grado',
            },
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='id_docente',
            field=models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='id_tip_grado',
            field=models.ForeignKey(db_column='id_tip_grado', on_delete=django.db.models.deletion.CASCADE, to='docente.TipoGrado'),
        ),
    ]
