# Generated by Django 2.0.3 on 2018-04-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_curso', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id_preferencia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='curso.Curso')),
            ],
            options={
                'db_table': 'preferencia',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_programa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
    ]
